-- ============================================================
-- SEED — real Sri Lakshmi Mart catalogue
-- Generated from the customer site data (js/data.js), so both
-- applications start from exactly the same products and prices.
-- Run after schema.sql. Re-runnable: conflicts are ignored.
-- ============================================================

insert into public.categories (slug,name,sort_order) values
  ('organic-malt','Malt',1),
  ('organic-readymix','Ready Mix',2),
  ('organic-masala','Masala',3),
  ('organic-laddu','Laddu',4),
  ('home-kitchen','Kitchen',5),
  ('home-cleaning','Cleaning',6),
  ('home-beauty','Beauty',7),
  ('home-home','Home',8),
  ('home-kids','Kids',9)
on conflict (slug) do nothing;

insert into public.products (sku,slug,name,category_id,description,benefits,how_to_use,price,image_url) values
  ('SLM-P001','sprouted-health-mix','Sprouted Health Mix',(select id from public.categories where slug='organic-malt'),'A wholesome multi-grain sprouted health mix rich in protein, fibre and essential vitamins.','{"High Protein","Rich in Fibre","Energy Boosting"}','Mix 3 tbsp in 250ml warm milk. Sweeten with jaggery.',120,'assets/products/p1.jpg'),
  ('SLM-P002','badam-mix','Badam Mix',(select id from public.categories where slug='organic-malt'),'Premium almond-based health mix blended with traditional grains for complete nutrition.','{"Rich in Healthy Fats","Boosts Brain Health","Natural Energy"}','Mix 2 tbsp in warm milk or water. Best served hot.',160,'assets/products/p2.jpg'),
  ('SLM-P003','sprouted-ragi-choco-malt','Sprouted Ragi Choco Malt',(select id from public.categories where slug='organic-malt'),'The perfect blend of sprouted ragi with a touch of natural cocoa for a delicious health drink.','{"Rich in Calcium","Iron","Natural Chocolate Flavour"}','Mix 2 tbsp in 200ml warm milk. Kids love it!',95,'assets/products/p3.jpg'),
  ('SLM-P004','pasumanjal-malt','Pasumanjal Malt',(select id from public.categories where slug='organic-malt'),'Traditional turmeric-based malt with immunity-boosting properties.','{"Anti-Inflammatory","Immunity Booster","Traditional Recipe"}','Mix 2 tsp in warm milk with a pinch of pepper.',80,'assets/products/p4.jpg'),
  ('SLM-P005','sprouted-ragi-malt','Sprouted Ragi Malt',(select id from public.categories where slug='organic-malt'),'Pure sprouted finger millet malt — rich in calcium and a powerhouse of nutrition.','{"Rich in Calcium","Iron","Aids Digestion"}','Mix 2 tbsp in 200ml warm milk or water. Add honey to taste.',80,'assets/products/p5.svg'),
  ('SLM-P006','sprouted-homemade-horlicks','Sprouted Homemade Horlicks',(select id from public.categories where slug='organic-malt'),'Our homemade version of the classic malt drink, made with sprouted grains and natural ingredients.','{"Multi-Grain","No Artificial Additives","Complete Nutrition"}','Mix 3 tbsp in warm milk for a filling health drink.',110,'assets/products/p6.svg'),
  ('SLM-P007','sprouted-kambu-malt','Sprouted Kambu Malt',(select id from public.categories where slug='organic-malt'),'Pearl millet malt with cooling properties — ideal for summer and growing children.','{"Cooling","Iron-Rich","Gluten-Free"}','Mix 2 tbsp in water or milk. Add jaggery or palm sugar.',80,'assets/products/p7.svg'),
  ('SLM-P008','multi-millet-dosai-mix','Multi Millet Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Premium multi-millet dosai mix for a healthy South Indian breakfast without compromise.','{"High Protein","Rich in Fibre","Multi-Grain"}','Mix with water to thin batter consistency. Cook on a hot tawa.',130,'assets/products/p8.svg'),
  ('SLM-P009','rava-dosai-mix','Rava Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Instant crispy rava dosai mix — restaurant quality at home in minutes.','{"Instant","Crispy Texture","Traditional Taste"}','Mix with water. Add finely chopped onion and serve hot with chutney.',110,'assets/products/p9.svg'),
  ('SLM-P010','karuppakavuni-mix','Karuppakavuni Mix',(select id from public.categories where slug='organic-readymix'),'Black rice porridge mix with powerful antioxidants and traditional nutritional benefits.','{"Rich in Antioxidants","Anthocyanin-Rich","Traditional Superfood"}','Cook 1 cup with 3 cups water or milk. Sweeten with jaggery.',130,'assets/products/p10.svg'),
  ('SLM-P011','instant-pongal-mix','Instant Pongal Mix',(select id from public.categories where slug='organic-readymix'),'Traditional Tamil festival Pongal in an instant mix — tastes just like the real thing.','{"Festival Traditional","Ready in 15 mins","Authentic Flavour"}','Cook with water and ghee. Garnish with pepper and cashews.',120,'assets/products/p11.svg'),
  ('SLM-P012','ragi-dosai-mix','Ragi Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Wholesome finger millet dosai mix — a nutritious alternative to regular rice dosai.','{"High Calcium","Iron","Great for Kids & Adults"}','Mix with water, rest 10 minutes. Cook on a non-stick tawa.',110,'assets/products/p12.jpg'),
  ('SLM-P019','thooyamalli-dosai-mix','Thooyamalli Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Pure white ponni rice dosai mix with a soft texture and authentic traditional taste.','{"Soft Texture","Traditional Taste","No Preservatives"}','Mix with water to batter consistency. Ferment 2 hrs and cook on tawa.',110,'assets/products/p19.svg'),
  ('SLM-P020','ada-dosai-mix','Ada Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Traditional Ada dosai mix made with rice and lentils for a thick, nutritious breakfast.','{"High Protein","Thick & Filling","Traditional Recipe"}','Mix with water, rest 30 minutes and cook on a greased tawa.',120,'assets/products/p20.svg'),
  ('SLM-P021','kambu-dosai-mix','Kambu Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Pearl millet dosai mix — a cooling, iron-rich healthy breakfast option.','{"Cooling","Iron-Rich","Gluten-Friendly"}','Mix with water to batter consistency and cook fresh on tawa.',110,'assets/products/p21.svg'),
  ('SLM-P022','thinai-millet-dosai-mix','Thinai Millet Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Foxtail millet dosai mix packed with iron and fibre for a wholesome breakfast.','{"Rich in Iron","High Fibre","Diabetic-Friendly"}','Mix with water, rest 10 minutes, and cook on a non-stick tawa.',110,'assets/products/p22.svg'),
  ('SLM-P023','kuthiraivali-millet-dosai-mix','Kuthiraivali Millet Dosai Mix',(select id from public.categories where slug='organic-readymix'),'Barnyard millet dosai mix — a light, digestible and nutritious morning meal.','{"Easy to Digest","Gluten-Free","Low Calorie"}','Mix with water and cook immediately on a hot tawa.',115,'assets/products/p23.svg'),
  ('SLM-P013','sambar-powder','Sambar Powder',(select id from public.categories where slug='organic-masala'),'Authentic homemade sambar powder with a perfect blend of hand-roasted spices.','{"Rich Aroma","Traditional Recipe","No Artificial Colours"}','Add 1–2 tsp per serving of sambar. Adjust to taste.',60,'assets/products/p13.jpg'),
  ('SLM-P014','biryani-masala','Biryani Masala',(select id from public.categories where slug='organic-masala'),'Premium homemade biryani masala with whole spices for an aromatic, authentic biryani.','{"Whole Spice Blend","Authentic Dum Flavour","No MSG"}','Use 2 tsp per kg rice. Add during cooking for best aroma.',70,'assets/products/p14.jpg'),
  ('SLM-P015','coriander-powder','Coriander Powder',(select id from public.categories where slug='organic-masala'),'Pure freshly ground coriander powder with an earthy, citrusy aroma.','{"Anti-Inflammatory","Improves Digestion","Natural Flavour"}','Use 1–2 tsp in gravies, curries, and marinades.',50,'assets/products/p15.svg'),
  ('SLM-P024','rasam-powder','Rasam Powder',(select id from public.categories where slug='organic-masala'),'Homemade rasam powder with a perfect tangy-spicy balance for comforting rasam.','{"Aids Digestion","Tangy Spice Blend","Traditional Taste"}','Add 1 tsp per serving of rasam. Adjust to taste.',55,'assets/products/p24.jpg'),
  ('SLM-P025','non-veg-masala','Non Veg Masala',(select id from public.categories where slug='organic-masala'),'Freshly ground non-veg masala with a rich blend of spices for chicken, mutton and fish.','{"Aromatic","Deep Flavour","No Artificial Colour"}','Marinate meat with 1–2 tsp masala. Cook as desired.',70,'assets/products/p25.jpg'),
  ('SLM-P026','turmeric-powder','Turmeric Powder',(select id from public.categories where slug='organic-masala'),'Pure sun-dried turmeric powder with a vibrant colour and strong anti-inflammatory properties.','{"Anti-Inflammatory","Immunity Boosting","Natural Colour"}','Add a pinch to curries, milk or rice for daily health benefits.',45,'assets/products/p26.svg'),
  ('SLM-P027','65-masala','65 Masala',(select id from public.categories where slug='organic-masala'),'Special spice blend for Chicken 65 and other crispy fry dishes — restaurant quality at home.','{"Bold & Spicy","Crispy Fry Blend","Authentic Taste"}','Mix with yogurt and meat. Marinate 30 mins. Deep fry or air fry.',65,'assets/products/p27.svg'),
  ('SLM-P028','cumin-powder','Cumin Powder',(select id from public.categories where slug='organic-masala'),'Freshly ground cumin powder with a warm, earthy aroma for everyday cooking.','{"Improves Digestion","Antioxidant-Rich","Natural Aroma"}','Add 1/2–1 tsp in gravies, rice dishes, and raitas.',50,'assets/products/p28.svg'),
  ('SLM-P016','varagu-laddu','Varagu Laddu',(select id from public.categories where slug='organic-laddu'),'Traditional kodo millet laddu sweetened with jaggery — a wholesome guilt-free sweet.','{"High Fibre","Low GI","Diabetic-Friendly"}','Enjoy 1–2 laddus as a healthy snack or dessert anytime.',95,'assets/products/p16.svg'),
  ('SLM-P017','thinai-laddu','Thinai Laddu',(select id from public.categories where slug='organic-laddu'),'Foxtail millet laddu with jaggery and ghee — energy-packed and nutritious.','{"Rich in Iron","Natural Energy","Traditional Sweet"}','Consume as a snack. Best enjoyed at room temperature.',95,'assets/products/p17.svg'),
  ('SLM-P018','kambu-laddu','Kambu Laddu',(select id from public.categories where slug='organic-laddu'),'Pearl millet laddu — a cooling, nutritious traditional sweet from Tamil Nadu.','{"Cooling Properties","Iron-Rich","Natural Sweetener"}','Have 1–2 laddus daily as a nutritious treat.',95,'assets/products/p18.svg'),
  ('SLM-P029','samai-laddu','Samai Laddu',(select id from public.categories where slug='organic-laddu'),'Little millet laddu with jaggery and ghee — light, digestible and traditionally nutritious.','{"Light & Digestible","Gluten-Free","Natural Energy"}','Have 1–2 laddus as a healthy snack any time of the day.',95,'assets/products/p29.svg'),
  ('SLM-A1','liquid-cleaning-brush-a1','Liquid Cleaning Brush',(select id from public.categories where slug='home-cleaning'),'Effective liquid cleaning brush for dishes and surfaces. Easy grip handle.','{}','',117,'assets/acc2x/a1.jpg'),
  ('SLM-A2','waterproof-mobile-cover-a2','Waterproof Mobile Cover',(select id from public.categories where slug='home-home'),'Waterproof mobile cover to protect your phone from water and dust.','{}','',128,'assets/acc2x/a2.jpg'),
  ('SLM-A3','toothbrush-case-a3','Toothbrush Case',(select id from public.categories where slug='home-beauty'),'Portable toothbrush case for travel. Keeps your brush hygienic.','{}','',115,'assets/acc2x/a3.jpg'),
  ('SLM-A4','potato-masher-tool-a4','Potato Masher Tool',(select id from public.categories where slug='home-kitchen'),'Heavy duty potato masher for smooth mashing. Ergonomic handle.','{}','',137,'assets/acc2x/a4.jpg'),
  ('SLM-A5','ss-watermelon-cutter-slicer-a5','SS Watermelon Cutter Slicer',(select id from public.categories where slug='home-kitchen'),'Stainless steel watermelon cutter and slicer.','{}','',115,'assets/acc2x/a5.jpg'),
  ('SLM-A6','wooden-handle-veg-peeler-a6','Wooden Handle Veg Peeler',(select id from public.categories where slug='home-kitchen'),'Premium wooden handle vegetable peeler. Sharp blade.','{}','',119,'assets/acc2x/a6.jpg'),
  ('SLM-A7','kitchen-dish-scrubber-brush-a7','Kitchen Dish Scrubber Brush',(select id from public.categories where slug='home-cleaning'),'Multi-purpose kitchen dish scrubber brush.','{}','',125,'assets/acc2x/a7.jpg'),
  ('SLM-A8','multi-cleaning-brush-a8','Multi Cleaning Brush',(select id from public.categories where slug='home-cleaning'),'Versatile multi-purpose cleaning brush.','{}','',131,'assets/acc2x/a8.jpg'),
  ('SLM-A9','nut-seafood-cracker-tool-a9','Nut & Seafood Cracker Tool',(select id from public.categories where slug='home-kitchen'),'Heavy duty nut and seafood cracker.','{}','',123,'assets/acc2x/a9.jpg'),
  ('SLM-A10','egg-cutter-slicer-2pc-a10','Egg Cutter & Slicer 2pc',(select id from public.categories where slug='home-kitchen'),'2-piece egg cutter and slicer set.','{}','',145,'assets/acc2x/a10.jpg'),
  ('SLM-A11','mini-corn-cutter-a11','Mini Corn Cutter',(select id from public.categories where slug='home-kitchen'),'Compact corn cutter removes kernels quickly.','{}','',131,'assets/acc2x/a11.jpg'),
  ('SLM-A12','premium-ss-cookie-cutter-set-a12','Premium SS Cookie Cutter Set',(select id from public.categories where slug='home-kitchen'),'Set of premium stainless steel cookie cutters.','{}','',119,'assets/acc2x/a12.jpg'),
  ('SLM-A13','ss-round-hot-pot-stand-a13','SS Round Hot Pot Stand',(select id from public.categories where slug='home-kitchen'),'Stainless steel round hot pot stand.','{}','',124,'assets/acc2x/a13.jpg'),
  ('SLM-A14','premium-apple-cutter-a14','Premium Apple Cutter',(select id from public.categories where slug='home-kitchen'),'Premium apple cutter that cores and slices in one press.','{}','',120,'assets/acc2x/a14.jpg'),
  ('SLM-A15','aluminium-foil-paper-roll-a15','Aluminium Foil Paper Roll',(select id from public.categories where slug='home-kitchen'),'Premium aluminium foil paper roll for cooking and storage.','{}','',137,'assets/acc2x/a15.jpg'),
  ('SLM-A16','ss-coconut-opener-a16','SS Coconut Opener',(select id from public.categories where slug='home-kitchen'),'Stainless steel coconut opener. Safe and easy to use.','{}','',130,'assets/acc2x/a16.jpg'),
  ('SLM-A17','safety-cover-socket-big-a17','Safety Cover Socket Big',(select id from public.categories where slug='home-home'),'Child-safe socket cover to prevent electric accidents.','{}','',104,'assets/acc2x/a17.jpg'),
  ('SLM-A18','stylish-mini-hair-claw-clips-12pc-a18','Stylish Mini Hair Claw Clips 12pc',(select id from public.categories where slug='home-beauty'),'Set of 12 stylish mini hair claw clips in assorted colors.','{}','',140,'assets/acc2x/a18.jpg'),
  ('SLM-A19','mosquito-incense-sticks-a19','Mosquito Incense Sticks',(select id from public.categories where slug='home-home'),'Effective mosquito repellent incense sticks.','{}','',111,'assets/acc2x/a19.jpg'),
  ('SLM-A20','scratcher-massage-tool-a20','Scratcher Massage Tool',(select id from public.categories where slug='home-beauty'),'Relaxing back scratcher and massage tool.','{}','',120,'assets/acc2x/a20.jpg'),
  ('SLM-A21','silicone-dish-scrubber-a21','Silicone Dish Scrubber',(select id from public.categories where slug='home-cleaning'),'Soft silicone dish scrubber. Heat resistant.','{}','',107,'assets/acc2x/a21.jpg'),
  ('SLM-A22','face-massage-ice-roller-a22','Face Massage Ice Roller',(select id from public.categories where slug='home-beauty'),'Cooling face massage ice roller.','{}','',128,'assets/acc2x/a22.jpg'),
  ('SLM-A23','magic-hair-wrap-towel-a23','Magic Hair Wrap Towel',(select id from public.categories where slug='home-beauty'),'Super absorbent magic hair wrap towel.','{}','',152,'assets/acc2x/a23.jpg'),
  ('SLM-A24','cable-protector-sleeve-a24','Cable Protector Sleeve',(select id from public.categories where slug='home-home'),'Protective sleeve for phone charging cables.','{}','',120,'assets/acc2x/a24.jpg'),
  ('SLM-A25','scalp-massager-comb-a25','Scalp Massager Comb',(select id from public.categories where slug='home-beauty'),'Scalp massager comb for improved circulation.','{}','',109,'assets/acc2x/a25.jpg'),
  ('SLM-A26','brass-wire-brush-a26','Brass Wire Brush',(select id from public.categories where slug='home-cleaning'),'Heavy duty brass wire brush for cleaning.','{}','',110,'assets/acc2x/a26.jpg'),
  ('SLM-A27','3in1-ac-vent-keyboard-cleaner-a27','3in1 AC Vent & Keyboard Cleaner',(select id from public.categories where slug='home-home'),'3-in-1 cleaning tool for AC vents and keyboards.','{}','',117,'assets/acc2x/a27.jpg'),
  ('SLM-A28','organic-coco-peat-powder-a28','Organic Coco Peat Powder',(select id from public.categories where slug='home-home'),'Organic coco peat powder for gardening.','{}','',131,'assets/acc2x/a28.jpg'),
  ('SLM-A29','metal-ball-air-pump-pin-a29','Metal Ball Air Pump Pin',(select id from public.categories where slug='home-home'),'Metal ball inflation pin for sports balls.','{}','',106,'assets/acc2x/a29.jpg'),
  ('SLM-A30','metal-thread-cutter-knife-a30','Metal Thread Cutter Knife',(select id from public.categories where slug='home-home'),'Sharp metal thread cutter knife for sewing.','{}','',118,'assets/acc2x/a30.jpg'),
  ('SLM-A31','gym-yoga-ring-a31','Gym Yoga Ring',(select id from public.categories where slug='home-beauty'),'Flexible gym yoga ring for stretching.','{}','',132,'assets/acc2x/a31.jpg'),
  ('SLM-A32','self-adhesive-wall-hooks-10pc-a32','Self Adhesive Wall Hooks 10pc',(select id from public.categories where slug='home-home'),'Set of 10 self-adhesive round wall hooks.','{}','',128,'assets/acc2x/a32.jpg'),
  ('SLM-A33','glass-shape-soap-box-a33','Glass Shape Soap Box',(select id from public.categories where slug='home-beauty'),'Stylish glass-shaped soap storage box.','{}','',126,'assets/acc2x/a33.jpg'),
  ('SLM-A34','double-sided-tape-3mtr-a34','Double Sided Tape 3mtr',(select id from public.categories where slug='home-home'),'Transparent double-sided tape 3 meters.','{}','',119,'assets/acc2x/a34.jpg'),
  ('SLM-A35','plastic-fidget-toy-a35','Plastic Fidget Toy',(select id from public.categories where slug='home-kids'),'Fun plastic fidget toy for stress relief.','{}','',117,'assets/acc2x/a35.jpg'),
  ('SLM-A36','mini-heat-sealer-machine-a36','Mini Heat Sealer Machine',(select id from public.categories where slug='home-kitchen'),'Mini electric heat sealer for plastic bags.','{}','',145,'assets/acc2x/a36.jpg'),
  ('SLM-A37','u-shaped-neck-pillow-a37','U-Shaped Neck Pillow',(select id from public.categories where slug='home-home'),'Comfortable U-shaped neck pillow for travel.','{}','',134,'assets/acc2x/a37.jpg'),
  ('SLM-A38','microfiber-wash-glove-a38','Microfiber Wash Glove',(select id from public.categories where slug='home-cleaning'),'Microfiber wash glove for gentle cleaning.','{}','',144,'assets/acc2x/a38.jpg'),
  ('SLM-A39','manual-swat-pest-control-a39','Manual Swat Pest Control',(select id from public.categories where slug='home-home'),'Manual swat for pest control.','{}','',124,'assets/acc2x/a39.jpg'),
  ('SLM-A40','handheld-scalp-head-massager-a40','Handheld Scalp Head Massager',(select id from public.categories where slug='home-beauty'),'Handheld scalp massager. Relieves stress.','{}','',134,'assets/acc2x/a40.jpg'),
  ('SLM-A41','chair-mobile-stand-a41','Chair Mobile Stand',(select id from public.categories where slug='home-home'),'Cute chair-shaped mobile phone stand.','{}','',125,'assets/acc2x/a41.jpg'),
  ('SLM-A42','plastic-wall-mobile-holder-a42','Plastic Wall Mobile Holder',(select id from public.categories where slug='home-home'),'Wall-mount plastic mobile holder.','{}','',121,'assets/acc2x/a42.jpg'),
  ('SLM-A43','bottle-cleaning-foam-brush-a43','Bottle Cleaning Foam Brush',(select id from public.categories where slug='home-cleaning'),'Foam brush for cleaning bottles and cups.','{}','',117,'assets/acc2x/a43.jpg'),
  ('SLM-A44','head-massager-comb-a44','Head Massager Comb',(select id from public.categories where slug='home-beauty'),'Relaxing head massager comb for scalp.','{}','',116,'assets/acc2x/a44.jpg'),
  ('SLM-A45','gym-hand-grip-2pc-a45','Gym Hand Grip 2pc',(select id from public.categories where slug='home-beauty'),'2-piece gym hand grip for workouts.','{}','',134,'assets/acc2x/a45.jpg'),
  ('SLM-A46','multani-matti-powder-100gm-a46','Multani Matti Powder 100gm',(select id from public.categories where slug='home-beauty'),'Pure Multani Matti powder for face pack.','{}','',112,'assets/acc2x/a46.jpg'),
  ('SLM-A47','multi-grip-toothbrush-holder-a47','Multi Grip Toothbrush Holder',(select id from public.categories where slug='home-beauty'),'Multi-grip toothbrush holder for family.','{}','',145,'assets/acc2x/a47.jpg'),
  ('SLM-A48','3pc-mini-wire-brush-set-a48','3pc Mini Wire Brush Set',(select id from public.categories where slug='home-cleaning'),'Set of 3 mini wire brushes for cleaning.','{}','',128,'assets/acc2x/a48.jpg'),
  ('SLM-A49','kids-colouring-book-5pc-set-a49','Kids Colouring Book 5pc Set',(select id from public.categories where slug='home-kids'),'Set of 5 colorful kids colouring books.','{}','',120,'assets/acc2x/a49.jpg'),
  ('SLM-A50','magic-broom-holder-a50','Magic Broom Holder',(select id from public.categories where slug='home-cleaning'),'Wall-mount magic broom holder.','{}','',121,'assets/acc2x/a50.jpg'),
  ('SLM-A51','baby-shower-cap-a51','Baby Shower Cap',(select id from public.categories where slug='home-kids'),'Soft baby shower cap for bath time.','{}','',129,'assets/acc2x/a51.jpg'),
  ('SLM-A52','underarms-pads-10pc-a52','Underarms Pads 10pc',(select id from public.categories where slug='home-beauty'),'Disposable underarm sweat pads.','{}','',137,'assets/acc2x/a52.jpg'),
  ('SLM-A53','2in1-portable-lint-remover-a53','2in1 Portable Lint Remover',(select id from public.categories where slug='home-home'),'Portable 2-in-1 lint remover.','{}','',124,'assets/acc2x/a53.jpg'),
  ('SLM-A54','toilet-gel-cleaner-a54','Toilet Gel Cleaner',(select id from public.categories where slug='home-cleaning'),'Effective toilet gel cleaner.','{}','',127,'assets/acc2x/a54.jpg'),
  ('SLM-A55','wall-mount-mobile-holder-a55','Wall Mount Mobile Holder',(select id from public.categories where slug='home-home'),'Self-adhesive wall mount mobile holder.','{}','',115,'assets/acc2x/a55.jpg'),
  ('SLM-A56','silicone-tap-extender-a56','Silicone Tap Extender',(select id from public.categories where slug='home-home'),'Silicone tap extender for children.','{}','',129,'assets/acc2x/a56.jpg'),
  ('SLM-A57','wall-mounted-self-adhesive-hanger-a57','Wall Mounted Self Adhesive Hanger',(select id from public.categories where slug='home-home'),'Self-adhesive wall hanger. No tools needed.','{}','',105,'assets/acc2x/a57.jpg'),
  ('SLM-A58','rice-washing-spoon-a58','Rice Washing Spoon',(select id from public.categories where slug='home-kitchen'),'Perforated rice washing spoon.','{}','',117,'assets/acc2x/a58.jpg'),
  ('SLM-A59','buddha-money-bank-coin-box-a59','Buddha Money Bank Coin Box',(select id from public.categories where slug='home-home'),'Decorative Buddha money bank coin box.','{}','',140,'assets/acc2x/a59.jpg'),
  ('SLM-A60','tortoise-money-bank-a60','Tortoise Money Bank',(select id from public.categories where slug='home-kids'),'Cute tortoise-shaped coin saving bank.','{}','',129,'assets/acc2x/a60.jpg'),
  ('SLM-A61','kids-water-color-painting-book-a61','Kids Water Color Painting Book',(select id from public.categories where slug='home-kids'),'Kids water color painting book with brush.','{}','',134,'assets/acc2x/a61.jpg'),
  ('SLM-A62','premium-textured-floor-mat-a62','Premium Textured Floor Mat',(select id from public.categories where slug='home-home'),'Premium textured anti-slip floor mat.','{}','',137,'assets/acc2x/a62.jpg'),
  ('SLM-A63','wetwisk-makeup-remover-wipes-a63','Wetwisk Makeup Remover Wipes',(select id from public.categories where slug='home-beauty'),'Gentle makeup remover wet wipes.','{}','',110,'assets/acc2x/a63.jpg'),
  ('SLM-A64','ss-pizza-cutter-wheel-a64','SS Pizza Cutter Wheel',(select id from public.categories where slug='home-kitchen'),'Stainless steel pizza cutter wheel.','{}','',142,'assets/acc2x/a64.jpg'),
  ('SLM-A65','small-kitchen-towel-a65','Small Kitchen Towel',(select id from public.categories where slug='home-kitchen'),'Absorbent small kitchen towel.','{}','',110,'assets/acc2x/a65.jpg'),
  ('SLM-A66','egg-yolk-separator-a66','Egg Yolk Separator',(select id from public.categories where slug='home-kitchen'),'Easy egg yolk separator for baking.','{}','',106,'assets/acc2x/a66.jpg'),
  ('SLM-A67','mini-sealing-machine-a67','Mini Sealing Machine',(select id from public.categories where slug='home-kitchen'),'Mini portable sealing machine for bags.','{}','',162,'assets/acc2x/a67.jpg'),
  ('SLM-A68','3mtr-cloth-drying-rope-a68','3mtr Cloth Drying Rope',(select id from public.categories where slug='home-home'),'3-meter strong cloth drying rope.','{}','',115,'assets/acc2x/a68.jpg')
on conflict (slug) do nothing;

-- size variants (organic foods)
insert into public.product_variants (product_id,label,grams,price) values
  ((select id from public.products where slug='sprouted-health-mix'),'200g',200,120),
  ((select id from public.products where slug='sprouted-health-mix'),'500g',500,280),
  ((select id from public.products where slug='sprouted-health-mix'),'1kg',1000,520),
  ((select id from public.products where slug='badam-mix'),'200g',200,160),
  ((select id from public.products where slug='badam-mix'),'500g',500,350),
  ((select id from public.products where slug='sprouted-ragi-choco-malt'),'200g',200,95),
  ((select id from public.products where slug='sprouted-ragi-choco-malt'),'500g',500,220),
  ((select id from public.products where slug='pasumanjal-malt'),'100g',100,80),
  ((select id from public.products where slug='pasumanjal-malt'),'200g',200,150),
  ((select id from public.products where slug='pasumanjal-malt'),'500g',500,340),
  ((select id from public.products where slug='sprouted-ragi-malt'),'200g',200,80),
  ((select id from public.products where slug='sprouted-ragi-malt'),'500g',500,180),
  ((select id from public.products where slug='sprouted-ragi-malt'),'1kg',1000,340),
  ((select id from public.products where slug='sprouted-homemade-horlicks'),'200g',200,110),
  ((select id from public.products where slug='sprouted-homemade-horlicks'),'500g',500,250),
  ((select id from public.products where slug='sprouted-kambu-malt'),'200g',200,80),
  ((select id from public.products where slug='sprouted-kambu-malt'),'500g',500,180),
  ((select id from public.products where slug='multi-millet-dosai-mix'),'500g',500,130),
  ((select id from public.products where slug='multi-millet-dosai-mix'),'1kg',1000,240),
  ((select id from public.products where slug='rava-dosai-mix'),'500g',500,110),
  ((select id from public.products where slug='rava-dosai-mix'),'1kg',1000,200),
  ((select id from public.products where slug='karuppakavuni-mix'),'500g',500,130),
  ((select id from public.products where slug='karuppakavuni-mix'),'1kg',1000,240),
  ((select id from public.products where slug='instant-pongal-mix'),'500g',500,120),
  ((select id from public.products where slug='instant-pongal-mix'),'1kg',1000,220),
  ((select id from public.products where slug='ragi-dosai-mix'),'500g',500,110),
  ((select id from public.products where slug='ragi-dosai-mix'),'1kg',1000,200),
  ((select id from public.products where slug='thooyamalli-dosai-mix'),'500g',500,110),
  ((select id from public.products where slug='thooyamalli-dosai-mix'),'1kg',1000,200),
  ((select id from public.products where slug='ada-dosai-mix'),'500g',500,120),
  ((select id from public.products where slug='ada-dosai-mix'),'1kg',1000,220),
  ((select id from public.products where slug='kambu-dosai-mix'),'500g',500,110),
  ((select id from public.products where slug='kambu-dosai-mix'),'1kg',1000,200),
  ((select id from public.products where slug='thinai-millet-dosai-mix'),'500g',500,110),
  ((select id from public.products where slug='thinai-millet-dosai-mix'),'1kg',1000,200),
  ((select id from public.products where slug='kuthiraivali-millet-dosai-mix'),'500g',500,115),
  ((select id from public.products where slug='kuthiraivali-millet-dosai-mix'),'1kg',1000,210),
  ((select id from public.products where slug='sambar-powder'),'100g',100,60),
  ((select id from public.products where slug='sambar-powder'),'250g',250,130),
  ((select id from public.products where slug='sambar-powder'),'500g',500,240),
  ((select id from public.products where slug='biryani-masala'),'100g',100,70),
  ((select id from public.products where slug='biryani-masala'),'250g',250,160),
  ((select id from public.products where slug='biryani-masala'),'500g',500,300),
  ((select id from public.products where slug='coriander-powder'),'100g',100,50),
  ((select id from public.products where slug='coriander-powder'),'250g',250,110),
  ((select id from public.products where slug='coriander-powder'),'500g',500,200),
  ((select id from public.products where slug='rasam-powder'),'100g',100,55),
  ((select id from public.products where slug='rasam-powder'),'250g',250,120),
  ((select id from public.products where slug='rasam-powder'),'500g',500,220),
  ((select id from public.products where slug='non-veg-masala'),'100g',100,70),
  ((select id from public.products where slug='non-veg-masala'),'250g',250,155),
  ((select id from public.products where slug='non-veg-masala'),'500g',500,290),
  ((select id from public.products where slug='turmeric-powder'),'100g',100,45),
  ((select id from public.products where slug='turmeric-powder'),'250g',250,100),
  ((select id from public.products where slug='turmeric-powder'),'500g',500,185),
  ((select id from public.products where slug='65-masala'),'100g',100,65),
  ((select id from public.products where slug='65-masala'),'250g',250,145),
  ((select id from public.products where slug='cumin-powder'),'100g',100,50),
  ((select id from public.products where slug='cumin-powder'),'250g',250,110),
  ((select id from public.products where slug='cumin-powder'),'500g',500,200),
  ((select id from public.products where slug='varagu-laddu'),'250g',250,95),
  ((select id from public.products where slug='varagu-laddu'),'500g',500,180),
  ((select id from public.products where slug='thinai-laddu'),'250g',250,95),
  ((select id from public.products where slug='thinai-laddu'),'500g',500,180),
  ((select id from public.products where slug='kambu-laddu'),'250g',250,95),
  ((select id from public.products where slug='kambu-laddu'),'500g',500,180),
  ((select id from public.products where slug='samai-laddu'),'250g',250,95),
  ((select id from public.products where slug='samai-laddu'),'500g',500,180)
on conflict (product_id,label) do nothing;

-- one inventory row per product; opening stock is 0 so the owner
-- enters real counts rather than inheriting invented numbers
insert into public.inventory (product_id, minimum_stock)
select id, 10 from public.products on conflict do nothing;
